language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://tinexw.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "f7O2bgRtSUFdSbHUoFReFQOo1TfC1XaGpcrbYMR0IUKVFXcADyxYEim3A8ptWIJtlJkFRBdl7SbXSkIi2RyWUhn7lKo+TY5e4+lzh0z5RI93rf5boMIjCGbWUSA0yzoaXoGTvfyMu1vrPSaS4zyr24EFt3FILiYJJ41CvOAFjV8GGVls71o6t9Zg/+DtIkIuxKLd3V1ecEvX8eIOVRmQG5OesMkCLL+YIp6J85XyHWwAN6txa95FMaghr2KTHTWh04vemwJ7EjOPayL+FXvHXljGmctHMZEJFee9p6smVgqQ6vsMO+2bALu7gBOGai7W8Xv3sRSOVwSkYWMqUFUiVax46NishATnw96Pv9U0t/E9V8TlQR9jIpiiU8YGZUYaBPXhXFkmTen4srV5ljvQ2UiLHUZ/IU6+Jfqm1Pf1q+t7EzV5ondIJB8JXkflFGZwSP0IJ9irK/CyftogqvdpNW6hEj53oVr0/lPBL1PapGZDB6uhSUbwqBm07kFoqJ3T/scATz6UYzQk47lfTej/uUpHLKbX3a0reLOB2YYDxYlMeubgP9lrjsDi5ohJXwJgtX9tsXAtmRK7XSuLjt1CT+hbgAbxcq+UbBTEbM4ooGVu7Jj/ulRAPN0t1Dh0YcsNZhq+aRccjpupzxbO7VEVjvaXgdRH5quSscnJkZ5np0s="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
